// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoBeUxvdoBYZVj39HJ6Ma4BqqpC69c4f0',
    appId: '1:507630109557:web:3eebf1bbdb0a7f8239493c',
    messagingSenderId: '507630109557',
    projectId: 'wellnessapp-6a022',
    authDomain: 'wellnessapp-6a022.firebaseapp.com',
    storageBucket: 'wellnessapp-6a022.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_m60vph4s1QBXa7SnVde_GALy1zpGT3s',
    appId: '1:507630109557:android:17bc83ed3c95a74839493c',
    messagingSenderId: '507630109557',
    projectId: 'wellnessapp-6a022',
    storageBucket: 'wellnessapp-6a022.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH2LXgzEIoioZ1K65SVyzSEqUvId4UD9U',
    appId: '1:507630109557:ios:de34fabc52779c6e39493c',
    messagingSenderId: '507630109557',
    projectId: 'wellnessapp-6a022',
    storageBucket: 'wellnessapp-6a022.firebasestorage.app',
    iosBundleId: 'com.example.wellnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH2LXgzEIoioZ1K65SVyzSEqUvId4UD9U',
    appId: '1:507630109557:ios:de34fabc52779c6e39493c',
    messagingSenderId: '507630109557',
    projectId: 'wellnessapp-6a022',
    storageBucket: 'wellnessapp-6a022.firebasestorage.app',
    iosBundleId: 'com.example.wellnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoBeUxvdoBYZVj39HJ6Ma4BqqpC69c4f0',
    appId: '1:507630109557:web:85ea1c0c9acc683f39493c',
    messagingSenderId: '507630109557',
    projectId: 'wellnessapp-6a022',
    authDomain: 'wellnessapp-6a022.firebaseapp.com',
    storageBucket: 'wellnessapp-6a022.firebasestorage.app',
  );
}
